- hosts: petclinic_web
  become: yes
  become_user: root

  tasks:
    - name: deploy petclinic
      copy: src=/var/jenkins_home/workspace/petclinic/build/libs/spring-petclinic-2.6.0.jar dest=/var/www/petclinic.jar

    - name: start petclinic
      shell: java -jar /var/www/*.jar
